### ISSUE TITLE
Redirect issue

### ISSUE THREAD

**Issue by mikey0000** [electrickiwi-nz/api-samples#13]
Hi, got a user complaining that the redirect has changed for HA, can you check the redirects for the client id please. I'd check myself but I'm overseas for the week.

https://github.com/mikey0000/ha-electric-kiwi/issues/6

thanks

**Comment by electrickiwi-nz** [comment]
@mikey0000 - thanks for raising this - seams strange that this is happening and have checked with the team. I will respond shortly with findings. Cheers !

**Comment by electrickiwi-nz** [comment]
@mikey0000 - we implemented reCapture on the welcome page for better security. For customers that were logging into the web portal some settings were being stored and shared which meant the redirect was getting crossed between the different clients. 

There was a deploy earlier today to fix this issue and it should be working correctly now. 

Cheers

**Comment by mikey0000** [comment]
Hey can you let me know when this is deployed, still not working as of right now.

**Comment by mikey0000** [comment]
Nvm tested again this morning and working.

**Comment by electrickiwi-nz** [comment]
@mikey0000 - great to hear that it is all go. Cheers, Matt
